version : "3"
services:
  nginx:
    build: ./nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/nginx/conf.d
    depends_on:
      - spring
      - react
  react:
    build: ./node_modules
    ports:
      - "3000:3000"
  spring:
    build:
      context: ./ersentinel_springboot
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:maraia://database:3306/ersentinel?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=ersentinel
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r!
    depends_on:
        - database
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env.db.dev
    volumes:
      - mariadb:/var/lib/mariadb

volumes:
  mariadb: