version : "3"
services:
  react:
    container_name: ersentinel_react
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - spring
  spring:
    container_name: ersentinel_springboot
    build:
      context: ./ersentinel_springboot
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/ersentinel?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=ersentinel
      - SPRING_DATASOURCE_PASSWORD=1q2w3e4r!
    ports:
        - "8080:8080"
    depends_on:
        - database
    extra_hosts:
      - host.docker.io.internal:host-gateway
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env.dev.db
    volumes:
      - mariadb:/var/lib/mariadb

volumes:
  mariadb: