spring:
  config:
    import:
      - api.yml
      - oauth2.yml
      - app.yml

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: #&33

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: false